apiVersion: v1
kind: ConfigMap
metadata:
  name: task6-config
data:
  DATABASE_HOST: postgres
  DATABASE_USER: myuser
  DATABASE_DB: myapp
  CACHE_ENABLED: "1"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: task6-secret
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dk
  DATABASE_PASSWORD_WITH_NEW_LINE: cGFzc3dkCg==
